
    create table Condiciones_Medicas (
        Condicion varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        primary key (id)
    )

    create table Condimentos (
        id bigint generated by default as identity (start with 1),
        cantidad integer,
        nombre varchar(255),
        recetaID bigint,
        primary key (id)
    )

    create table Consultas (
        id bigint generated by default as identity (start with 1),
        fecha varbinary(255),
        parametros varchar(255),
        user_id bigint,
        primary key (id)
    )

    create table Consultas_Recetas (
        Consultas_id bigint not null,
        lista_id bigint not null
    )

    create table Favoritas (
        Usuarios_id bigint not null,
        historialRecetas_id bigint not null
    )

    create table Grupos (
        id bigint generated by default as identity (start with 1),
        interesesJuntos varchar(255),
        nombre varchar(255),
        primary key (id)
    )

    create table Grupos_Usuarios (
        Grupos_id bigint not null,
        integrantes_id bigint not null
    )

    create table Ingredientes (
        id bigint generated by default as identity (start with 1),
        caloriasIndividuales integer,
        cantidad integer,
        nombre varchar(255),
        recetaID bigint,
        primary key (id)
    )

    create table Monitores_Sincronicos (
        Tipo varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        horarios varbinary(255),
        listaVeganosJunta varchar(255),
        primary key (id)
    )

    create table Monitores_Sincronicos_Recetas_Consultadas_Sincronicas (
        Monitores_Sincronicos_id bigint not null,
        listaMas_id bigint not null,
        listaFem_id bigint not null,
        listaConsultas_id bigint not null
    )

    create table Recetas (
        tipo varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        descripcion varchar(255),
        dificultad integer,
        nombre varchar(255),
        publica boolean,
        temporada_id bigint,
        subReceta_id bigint,
        usuarioId bigint,
        primary key (id)
    )

    create table Recetas_Consultadas_Sincronicas (
        id bigint generated by default as identity (start with 1),
        receta varchar(255),
        repeticiones integer,
        primary key (id)
    )

    create table Rutinas (
        TipoRutina varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        nivelEjercicio integer,
        primary key (id)
    )

    create table Solicitudes_De_Nuevos_Usuarios (
        id bigint generated by default as identity (start with 1),
        estado integer,
        usuario_id bigint,
        primary key (id)
    )

    create table Temporadas (
        TipoTemporada varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        fechaCelebracion varbinary(255),
        nombre varchar(255),
        primary key (id)
    )

    create table Usuarios (
        id bigint generated by default as identity (start with 1),
        altura numeric(19,2),
        comidasQueGustanJuntas varchar(255),
        comidasQueNoGustanJuntas varchar(255),
        dirMail varchar(255),
        fechaNacimiento varbinary(255),
        nombre varchar(255),
        opcionConsultasFavoritas boolean,
        pendiente boolean,
        peso numeric(19,2),
        sexo integer,
        rutina_id bigint,
        primary key (id)
    )

    create table Usuarios_Condiciones_Medicas (
        Usuarios_id bigint not null,
        condicionesMedicas_id bigint not null
    )

    alter table Condimentos 
        add constraint FK_1soce501867b66fmb7omcseuy 
        foreign key (recetaID) 
        references Recetas

    alter table Consultas 
        add constraint FK_7e7yr6wjlrudy75hp80wsdav1 
        foreign key (user_id) 
        references Usuarios

    alter table Consultas_Recetas 
        add constraint FK_hj9idou1f5170tm4jouf4787n 
        foreign key (lista_id) 
        references Recetas

    alter table Consultas_Recetas 
        add constraint FK_kskv9ehv0yfx3bhrrc249ao76 
        foreign key (Consultas_id) 
        references Consultas

    alter table Favoritas 
        add constraint FK_g0xwsaeo49q2ap2sg039whtjw 
        foreign key (historialRecetas_id) 
        references Recetas

    alter table Favoritas 
        add constraint FK_32ugvc7l541bkln3a3lnv5nq6 
        foreign key (Usuarios_id) 
        references Usuarios

    alter table Grupos_Usuarios 
        add constraint FK_oark47iachnftknig0ca0kxvc 
        foreign key (integrantes_id) 
        references Usuarios

    alter table Grupos_Usuarios 
        add constraint FK_56dsmy97n62tm6fienfrlku85 
        foreign key (Grupos_id) 
        references Grupos

    alter table Ingredientes 
        add constraint FK_oq4ipql3d7okpnv7efobp8q15 
        foreign key (recetaID) 
        references Recetas

    alter table Monitores_Sincronicos_Recetas_Consultadas_Sincronicas 
        add constraint FK_tgor36c6rwijk08gmlk9tptkp 
        foreign key (listaMas_id) 
        references Recetas_Consultadas_Sincronicas

    alter table Monitores_Sincronicos_Recetas_Consultadas_Sincronicas 
        add constraint FK_poj6ar1d8y5nekwg5dcev59ok 
        foreign key (Monitores_Sincronicos_id) 
        references Monitores_Sincronicos

    alter table Monitores_Sincronicos_Recetas_Consultadas_Sincronicas 
        add constraint FK_48js8fi0lsb53k5wjhp0hryqv 
        foreign key (listaFem_id) 
        references Recetas_Consultadas_Sincronicas

    alter table Monitores_Sincronicos_Recetas_Consultadas_Sincronicas 
        add constraint FK_86sbmpgx6nshsgg4m5dn77dhn 
        foreign key (listaConsultas_id) 
        references Recetas_Consultadas_Sincronicas

    alter table Monitores_Sincronicos_Recetas_Consultadas_Sincronicas 
        add constraint FK_poj6ar1d8y5nekwg5dcev59ok 
        foreign key (Monitores_Sincronicos_id) 
        references Monitores_Sincronicos

    alter table Recetas 
        add constraint FK_1du325u2coatk26ypau11p2v0 
        foreign key (temporada_id) 
        references Temporadas

    alter table Recetas 
        add constraint FK_qrmgidvo43xgt6k4qnmyig8l8 
        foreign key (subReceta_id) 
        references Recetas

    alter table Recetas 
        add constraint FK_fyykc1i7xx0jwpwn16fgq5781 
        foreign key (usuarioId) 
        references Usuarios

    alter table Solicitudes_De_Nuevos_Usuarios 
        add constraint FK_erpqhhbco3ls3p6pre4rolpv0 
        foreign key (usuario_id) 
        references Usuarios

    alter table Usuarios 
        add constraint FK_1v0wmu5y9o3ijifw4y9bno0nn 
        foreign key (rutina_id) 
        references Rutinas

    alter table Usuarios_Condiciones_Medicas 
        add constraint FK_5ajnfi7iyqiitfk2p8k3cm3vn 
        foreign key (condicionesMedicas_id) 
        references Condiciones_Medicas

    alter table Usuarios_Condiciones_Medicas 
        add constraint FK_sglenlt1wmgfdybsla19myibr 
        foreign key (Usuarios_id) 
        references Usuarios
